### ISSUE TITLE
composer require giantbomb/giantbomb notworking

### ISSUE THREAD

**Issue by asifagaria** [amalfra/giantbomb#6]
composer require giantbomb/giantbomb notworking

**Comment by amalfra** [comment]
Isn't below the error that you got?
```
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Root composer.json requires giantbomb/giantbomb ^2.0 -> satisfiable by giantbomb/giantbomb[v2.0.0].
    - giantbomb/giantbomb v2.0.0 requires ext-redis * -> it is missing from your system. Install or enable PHP's redis extension.
```

If yes then please enable PHP's Redis extension and then try the install again. https://github.com/phpredis/phpredis/blob/develop/INSTALL.markdown - this is a documentation on how to install it.
If you are using ubuntu then run the following command - ```sudo apt-get install php7.x.x-redis``` where x.x is your PHP version. for eg if you are using PHP v7.4.3 then run ```sudo apt-get install php7.4.3-redis```.

**Comment by amalfra** [comment]
@asifagaria Please feel free to reopen if the issue still persists.
